apiVersion: apps/v1
kind: Deployment
metadata:
  name: employeeapp-deployment
  namespace: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
      version: v1
  template:
    metadata:
      labels:
        app: employees
        version: v1
    spec:
      containers:
      - name: employeeapp
        image: 128140924817.dkr.ecr.us-east-1.amazonaws.com/test:v1
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: employeeapp-secret

