apiVersion: apps/v1
kind: Deployment
metadata:
  name: employeeappv2-deployment
  namespace: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
      version: v2
  template:
    metadata:
      labels:
        app: employees
        version: v2
    spec:
      containers:
      - name: employeeappv2
        image: 128140924817.dkr.ecr.us-east-1.amazonaws.com/test:v2
        ports:
        - containerPort: 8080
        env:
        - name: APP_COLOR
          value: blue  
        envFrom:
        - secretRef:
            name: employeeapp-secret

