apiVersion: v1
kind: Service
metadata:
  name: employeeapp-service
  namespace: webapp
spec:
  selector:
    app: employees
    version: v1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
       

